src/main/java/org/zisist/model/Configuration.java
package org.zisist.model;

/**
 * This class holds the configuration needed by the algorithm<br>
 * inside {@link org.zisist.leaderboard.LeaderboardHandler}
 *
 * Created by zis.tax@gmail.com on 12/10/2012 at 2:09 AM
 */
public class Configuration {
    private final String configurationName;
    private final String email;

    public Configuration(String configurationName, String email) {
        this.configurationName = configurationName;
        this.email = email;
    }

    public String getConfigurationName() {
        return configurationName;
    }

    public String getEmail() {
        return email;
    }
}

src/main/java/org/zisist/model/TopPlayer.java
package org.zisist.model;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Represents a player entity in a leaderboard
 * Created by zis.tax@gmail.com on 03/10/2012 at 1:38 AM
 */
@XmlRootElement
public class TopPlayer {
    private String name;
    private long points;
    private long kills;
    private String country;

    public TopPlayer() {}

    public TopPlayer(String name, long points, long kills, String country) {
        this.name = name;
        this.points = points;
        this.kills = kills;
        this.country = country;
    }


    public String getName() {
        return name;
    }

    public String getCountry() {
        return country;
    }

    public long getPoints() {
        return points;
    }

    public long getKills() {
        return kills;
    }

    public void setKills(long kills) {
        this.kills = kills;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public void setPoints(long points) {
        this.points = points;
    }
}

src/main/java/org/zisist/model/TopPlayerComparatorByPoints.java
package org.zisist.model;

import java.util.Comparator;

/**
 * Comparator that sorts a collection of TopPlayer objects in descending order based on the <br>
 * player's points
 * Created by zis.tax@gmail.com on 08/10/2012 at 2:58 AM
 */
public class TopPlayerComparatorByPoints implements Comparator<TopPlayer> {
    @Override
    public int compare(TopPlayer topPlayer, TopPlayer topPlayer1) {
        if (topPlayer.getPoints() < topPlayer1.getPoints()) {
            return 1;
        } else if (topPlayer.getPoints() > topPlayer1.getPoints()) {
            return -1;
        }
        return 0;
    }
}

src/main/java/org/zisist/model/xml/Leaderboard.java
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.12 at 01:31:13 AM EEST 
//


package org.zisist.model.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for leaderboard complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leaderboard">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="input_uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="input_analyzer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leaderboard", propOrder = {
    "inputUri",
    "inputAnalyzer"
})
@XmlRootElement(name = "leaderboard")
public class Leaderboard {

    @XmlElement(name = "input_uri", required = true)
    protected String inputUri;
    @XmlElement(name = "input_analyzer", required = true)
    protected String inputAnalyzer;

    public Leaderboard() {}

    public Leaderboard(String inputAnalyzer, String inputURI) {
        this.inputAnalyzer = inputAnalyzer;
        this.inputUri = inputURI;
    }

    /**
     * Gets the value of the inputUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputUri() {
        return inputUri;
    }

    /**
     * Sets the value of the inputUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputUri(String value) {
        this.inputUri = value;
    }

    /**
     * Gets the value of the inputAnalyzer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputAnalyzer() {
        return inputAnalyzer;
    }

    /**
     * Sets the value of the inputAnalyzer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputAnalyzer(String value) {
        this.inputAnalyzer = value;
    }

}

src/main/java/org/zisist/model/xml/LeaderboardConfiguration.java
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.12 at 01:31:13 AM EEST 
//


package org.zisist.model.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for leaderboard_configuration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leaderboard_configuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="leaderboards" type="{}leaderboards"/>
 *         &lt;element name="merger" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leaderboard_configuration", propOrder = {
    "description",
    "leaderboards",
    "merger",
    "publisher"
})
@XmlRootElement(name = "leaderboard_configuration")
public class LeaderboardConfiguration {

    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected Leaderboards leaderboards;
    @XmlElement(required = true)
    protected String merger;
    @XmlElement(required = true)
    protected String publisher;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the leaderboards property.
     * 
     * @return
     *     possible object is
     *     {@link Leaderboards }
     *     
     */
    public Leaderboards getLeaderboards() {
        return leaderboards;
    }

    /**
     * Sets the value of the leaderboards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Leaderboards }
     *     
     */
    public void setLeaderboards(Leaderboards value) {
        this.leaderboards = value;
    }

    /**
     * Gets the value of the merger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerger() {
        return merger;
    }

    /**
     * Sets the value of the merger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerger(String value) {
        this.merger = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublisher(String value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}

src/main/java/org/zisist/model/xml/LeaderboardConfigurations.java
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.12 at 01:31:13 AM EEST 
//


package org.zisist.model.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for leaderboard_configurations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leaderboard_configurations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="leaderboard_configuration" type="{}leaderboard_configuration" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leaderboard_configurations", propOrder = {
    "leaderboardConfiguration"
})
@XmlRootElement(name = "leaderboard_configurations")
public class LeaderboardConfigurations {

    @XmlElement(name = "leaderboard_configuration", required = true)
    protected List<LeaderboardConfiguration> leaderboardConfiguration;

    /**
     * Gets the value of the leaderboardConfiguration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leaderboardConfiguration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLeaderboardConfiguration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LeaderboardConfiguration }
     * 
     * 
     */
    public List<LeaderboardConfiguration> getLeaderboardConfiguration() {
        if (leaderboardConfiguration == null) {
            leaderboardConfiguration = new ArrayList<LeaderboardConfiguration>();
        }
        return this.leaderboardConfiguration;
    }

}

src/main/java/org/zisist/web/ConfigurationBean.java
package org.zisist.web;

import org.apache.log4j.Logger;
import org.springframework.util.StopWatch;
import org.zisist.SpringApplicationContext;
import org.zisist.conf.ConfigurationLoader;
import org.zisist.leaderboard.LeaderboardHandler;
import org.zisist.model.Configuration;
import org.zisist.model.xml.LeaderboardConfiguration;
import org.zisist.utils.WebKeys;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by zis.tax@gmail.com on 08/10/2012 at 11:31 PM
 */
public class ConfigurationBean {
    private static Logger log = Logger.getLogger(ConfigurationBean.class);
    private String email;
    private String configurationName;
    private String description;
    private LeaderboardHandler leaderboardsHandler;
    private ConfigurationLoader leaderConfigurationLoader;
    private LeaderboardConfiguration selectedLeaderboardConf;
    private Boolean multithreaded;

    public ConfigurationBean() {
        configurationName = "";
        email = "";
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

    public String getConfigurationName() {
        return configurationName;
    }

    public void setConfigurationName(String configurationName) {
        this.configurationName = configurationName;
    }

    public Object execute() {
        Configuration configuration = new Configuration(configurationName, email);
        try {
            String leaderboardHandlerName = (multithreaded != null && multithreaded) ? WebKeys.LEADERBOARD_HANDLER_MULTITHREAD : WebKeys.LEADERBOARD_HANDLER_SINGLETHREAD;
            leaderboardsHandler = SpringApplicationContext.getBean(leaderboardHandlerName, LeaderboardHandler.class);
            StopWatch watch = new StopWatch();
            watch.start();
            leaderboardsHandler.handleLeaderboards(configuration);
            watch.stop();
            log.info("Results unified successfully!");
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,
                    "Action completed Successfully.Execution Time : " + watch.getTotalTimeSeconds()+ " sec!",
                    "Action completed Successfully.Execution Time : " + watch.getTotalTimeSeconds()+ " sec!"));
        } catch (Exception e) {
            log.error("Something went wrong during results unification!", e);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
                    "An error occurred! Details : " + e.getMessage(), "An error occurred! Details : " + e.getMessage()));
        }

        return null;
    }

    public LeaderboardHandler getLeaderboardsHandler() {
        return leaderboardsHandler;
    }

    public void setLeaderboardsHandler(LeaderboardHandler leaderboardsHandler) {
        this.leaderboardsHandler = leaderboardsHandler;
    }

    public void setLeaderConfigurationLoader(ConfigurationLoader leaderConfigurationLoader) {
        this.leaderConfigurationLoader = leaderConfigurationLoader;
    }

    public ConfigurationLoader getLeaderConfigurationLoader() {
        return leaderConfigurationLoader;
    }

    public Object getConfigurationDescription() {
        if (configurationName != null) {
            description = leaderConfigurationLoader.getConfiguration(configurationName).getDescription();
        }
        return description;
    }

    public Map<String, String> getAvailableConfigurations() {
        Map<String, String> values = new LinkedHashMap<String, String>();
        List<LeaderboardConfiguration> configurations = leaderConfigurationLoader.getAvailableConfigurations();
        for(LeaderboardConfiguration conf : configurations) {
            values.put(conf.getName(), conf.getName());
        }
        return values;
    }

    public Object assignConfiguration() {
        selectedLeaderboardConf = leaderConfigurationLoader.getConfiguration(configurationName);
        return null;  //To change body of created methods use File | Settings | File Templates.
    }

    public LeaderboardConfiguration getSelectedLeaderboardConf() {
        return selectedLeaderboardConf;
    }

    public void setSelectedLeaderboardConf(LeaderboardConfiguration selectedLeaderboardConf) {
        this.selectedLeaderboardConf = selectedLeaderboardConf;
    }

    public Boolean getMultithreaded() {
        return multithreaded;
    }

    public void setMultithreaded(Boolean multithreaded) {
        this.multithreaded = multithreaded;
    }
}

src/main/webapp/index.jsp
<html>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib prefix="a4j" uri="http://richfaces.org/a4j" %>
<%@ taglib prefix="rich" uri="http://richfaces.org/rich" %>
<head>
    <%@ page contentType="text/html;charset=UTF-8" language="java" %>
    <meta http-equiv=Content-Type content="text/html; charset=utf-8">
    <title>Leaderboard</title>
    <link rel="STYLESHEET" type="text/css" href="styles/css.css">
</head>
<f:view>
    <f:loadBundle basename="messages" var="translationBundle"/>
    <body>
    <a4j:keepAlive beanName="confBean"/>
    <a4j:status id="ajaxStatus1" onstart="#{rich:component('pleaseWaitPanel')}.show();" onstop="#{rich:component('pleaseWaitPanel')}.hide();" />
    <h:form>
        <h:panelGrid id="mergerPanel" columns="1" style="margin-left:1%;" cellspacing="5">
            <%--    Configuration drop-down menu    --%>
            <h:panelGroup>
                <h:outputText value="Configuration : " style="font-weight:bold;"/>
                <h:selectOneMenu id="configuration" value="#{confBean.configurationName}" required="true">
                    <f:selectItem itemValue="" itemLabel=""/>
                    <f:selectItems value="#{confBean.availableConfigurations}"/>
                    <a4j:support event="onchange" action="#{confBean.assignConfiguration}" reRender="mergerPanel" ajaxSingle="true"/>
                </h:selectOneMenu>
                <rich:message for="configuration">
                    <f:facet name="errorMarker">
                        <h:graphicImage value="images/button_drop.png"/>
                    </f:facet>
                    <f:facet name="infoMarker">
                        <h:graphicImage value="images/button_ok.png"/>
                    </f:facet>
                    <f:facet name="warnMarker">
                        <h:graphicImage value="images/exclamation.png"/>
                    </f:facet>
                </rich:message>
            </h:panelGroup>

            <%--    Configuration description   --%>
            <h:panelGroup id="descriptionPanel">
                <h:panelGroup rendered="#{confBean.configurationName ne ''}">
                    <h:outputText value="Description : " style="font-weight:bold;"/>
                    <h:outputLabel value="#{confBean.configurationDescription}" escape="false"/>
                </h:panelGroup>
            </h:panelGroup>

            <%--    Additional Configuration    --%>
            <h:panelGroup id="emailPanel">
                <h:panelGroup rendered="#{confBean.selectedLeaderboardConf.publisher eq 'emailPublisher'}">
                    <h:outputText value="Email : " style="font-weight:bold;"/>
                    <h:inputText id="email" value="#{confBean.email}" required="true">
                        <f:validator validatorId="zisist.EmailValidator"/>
                    </h:inputText>
                    <rich:message for="email">
                        <f:facet name="errorMarker">
                            <h:graphicImage value="images/button_drop.png"/>
                        </f:facet>
                        <f:facet name="infoMarker">
                            <h:graphicImage value="images/button_ok.png"/>
                        </f:facet>
                        <f:facet name="warnMarker">
                            <h:graphicImage value="images/exclamation.png"/>
                        </f:facet>
                    </rich:message>
                </h:panelGroup>
            </h:panelGroup>

            <h:panelGroup>
                <h:panelGroup rendered="#{confBean.configurationName eq 'multiThreadSupportConfiguration'}">
                    <h:selectBooleanCheckbox id="checkbox" value="#{confBean.multithreaded}" title="click it to select or deselect"/>
                    <h:outputText value="Multithreaded Execution"/>
                </h:panelGroup>
            </h:panelGroup>
            <%--    Execute algorithm steps    --%>
            <h:panelGrid columns="1">
                <a4j:commandButton id="publishResults" process="emailPanel" value="Publish" action="#{confBean.execute}" reRender="mergerPanel"/>
                <rich:messages globalOnly="true" id="generalMessages">
                    <f:facet name="errorMarker">
                        <h:graphicImage value="/images/button_drop.png"/>
                    </f:facet>
                    <f:facet name="infoMarker">
                        <h:graphicImage value="/images/button_ok.png"/>
                    </f:facet>
                </rich:messages>
            </h:panelGrid>
        </h:panelGrid>
    </h:form>
    </body>
    <rich:modalPanel id="pleaseWaitPanel" height="80" autosized="true" zindex="2001"
                     style="background-color:transparent;margin-left: auto;margin-right: auto;border:none;"
                     shadowOpacity="0">
        <h:graphicImage value="/images/ajax-loader-Big-snake.gif"/>
    </rich:modalPanel>
</f:view>
</html>

src/main/webapp/start.jsp
<%--
  Created by IntelliJ IDEA.
  User: zisis
  Date: 10/26/12
  Time: 12:10 AM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title></title>
</head>
<body>
<jsp:forward page="/index.faces"/>
</body>
</html>